return {
  "RRethy/base16-nvim",
  lazy = false, -- MUST load immediately
  priority = 1000, -- MUST load before UI plugins
  config = function()
    -- This file is generated by Matugen
    require "generated.colors"
  end,
}
